### PR TITLE
Added backup of sudoers files

### LINKED ISSUE #71: Add /etc/sudoers to the file backup list

### PR DESCRIPTION
**Pull request by reaperzn**
Resolves #71

### CODE REVIEW

**Comment by StephenBrown2** [comment]
This backs up the files, but doesn't perform a diff. If that's expected, then it's working fine.

Also, I noticed that all the files get dumped in the top level dir, which could lead to collisions, however unlikely, but more importantly gives no indication of where the file came from if someone was to look at the configsnap directory by themselves.

**Comment by reaperzn** [comment]
@StephenBrown2 I had forgotten to add the sudoers file to the compare list. I have also now built in the functionality to backup the directory structure including the comparison for all files within that directory. 

Please test and let me know if there are any further issues

**Comment by StephenBrown2** [comment]
Cool! Looks better, though by all the files, I meant *all* the files. Ideally it'd be nice to copy the dir structure of each file that gets copied. I know that significantly alters the previous functionality of configsnap, but makes it much better if one wanted to archive the directory.

So far, looks like the main purpose of this PR is working without issues in my test though. :+1:

**Comment by reaperzn** [comment]
@StephenBrown2 Thanks for testing that. 

While I do see a small advantage of creating full directory structures for all the files, that would require quite a reasonable amount of overhauling to get all the other functionality to work as expected. For now I think we will keep things as they are with the default named files. The clashes are much more likely when you have user-defined filenames as found in directories similar to sudoers.d.

**Review by rhodesn — APPROVED** [review]

**Pull request merged**
