### PR TITLE
filtering out update line in pcs status

### PR DESCRIPTION
**Pull request by popindavibe**
to make the diff relevant so we can include 'pcs_status` it to the diff stage.

### CODE REVIEW

**Comment by popindavibe** [comment]
This is addressing #112 
@nrhodes91 I update the version to match current release (as version in file is still showing 0.17.1). Is that alright?

**Comment by rhodesn** [comment]
@popindavibe thanks for catching the version mismatch. I need to set something up before I can test this; should be done by this evening.

**Comment by rhodesn** [comment]
@popindavibe would it be worth converting line 605 to use the new filter logic rather than the `sed` pipe?
```python
run.run_command(['bash', '-c', 'ip a s | sed "/^\s\+valid_lft.*/d"'],
                'ip_addresses', fail_ok=False, sort=False)  # noqa: W605
```

Other than that it looks good.

Also, for another PR, should we look to do something similar with the `crm_mon` output (I'm not able to review test output at the moment)?

**Comment by popindavibe** [comment]
yes to both questions @nrhodes91 

I pushed the `sed` change accordingly (thanks!)
Also I realised I set the new `regexp_filter` to the wrong `pcs` command (contraint instead of status), also fixed ;-)

**Pull request merged**
