### PR TITLE
PHP - record basic configuration

### PR DESCRIPTION
**Pull request by appyoo**
Test for presence of php.ini, and if so
* Backup php.ini
* Backup /etc/php.d
* Check for pecl binary and if so
* Record pecl list

### CODE REVIEW

**Comment by piersc** [comment]
Thanks for the PR!  Couple of comments:

- Could you copy the directory /etc/php.d to \<workdir\>/php.d.\<phase\> rather than copying all the files straight into \<workdir\>/\<filename\>.\<phase\>
- Best not to sort php_modules since I think that's already always sorted, and contains section headings (e.g. [PHP Modules], [Zend Modules]). I think the same might be true of pecl list as well?

**Comment by appyoo** [comment]
Pushed 0b5f51505ee4bb29b26ca3b9863d38cce59d7e4d
This really needs a better pair of python eyes although my basic testing looks OK

**Comment by appyoo** [comment]
PR ready for re-review

**Comment by piersc** [comment]
Looks good, thanks

**Pull request merged**
